In [54]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np

In [55]:
data = pd.read_csv("../data/data.csv", delimiter=";")

In [56]:
data.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [57]:
data.describe()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP
count,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,...,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000
mean,1.178571,18.669078,1.727848,8856.642631,0.890823,4.577758,132.613314,1.873192,19.561935,22.275316,...,0.137658,0.541817,6.232143,8.063291,4.435805,10.230206,0.150316,11.566139,1.228029,0.001969
std,0.605747,17.484682,1.313793,2063.566416,0.311897,10.216592,13.188332,6.914514,15.603186,15.343108,...,0.690880,1.918546,2.195951,3.947951,3.014764,5.210808,0.753774,2.663850,1.382711,2.269935
min,1.000000,1.000000,0.000000,33.000000,0.000000,1.000000,95.000000,1.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.600000,-0.800000,-4.060000
25%,1.000000,1.000000,1.000000,9085.000000,1.000000,1.000000,125.000000,1.000000,2.000000,3.000000,...,0.000000,0.000000,5.000000,6.000000,2.000000,10.750000,0.000000,9.400000,0.300000,-1.700000
50%,1.000000,17.000000,1.000000,9238.000000,1.000000,1.000000,133.100000,1.000000,19.000000,19.000000,...,0.000000,0.000000,6.000000,8.000000,5.000000,12.200000,0.000000,11.100000,1.400000,0.320000
75%,1.000000,39.000000,2.000000,9556.000000,1.000000,1.000000,140.000000,1.000000,37.000000,37.000000,...,0.000000,0.000000,7.000000,10.000000,6.000000,13.333333,0.000000,13.900000,2.600000,1.790000
max,6.000000,57.000000,9.000000,9991.000000,1.000000,43.000000,190.000000,109.000000,44.000000,44.000000,...,12.000000,19.000000,23.000000,33.000000,20.000000,18.571429,12.000000,16.200000,3.700000,3.510000

In [58]:
data.shape

(4424, 37)

In [59]:
data.isnull().sum()

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance\t                      0
Previous qualification                            0
Previous qualification (grade)                    0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Admission grade                                   0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular units 1st sem (credited)               0
Curricular units 1st sem (enrolled)               0
Curricular units 1st sem (evaluations)            0
Curricular units 1st sem (approved)               0
Curricular units 1st sem (grade)                  0
Curricular units 1st sem (without evaluations)    0
Curricular units 2nd sem (credited)               0
Curricular units 2nd sem (enrolled)               0
Curricular units 2nd sem (evaluations)            0
Curricular units 2nd sem (approved)               0
Curricular units 2nd sem (grade)                  0
Curricular units 2nd sem (without evaluations)    0
Unemployment rate                                 0
Inflation rate                                    0
GDP                                               0
Target                                            0
dtype: int64

In [60]:
data["Target"].value_counts()

Target
Graduate    2209
Dropout     1421
Enrolled     794
Name: count, dtype: int64

In [61]:
df = data.copy()

In [62]:
# Membuat dictionary mapping berdasarkan dokumentasi yang kamu berikan
app_mode_map = {
    1: '1st phase - general contingent',
    2: 'Ordinance No. 612/93',
    5: '1st phase - special contingent (Azores Island)',
    7: 'Holders of other higher courses',
    10: 'Ordinance No. 854-B/99',
    15: 'International student (bachelor)',
    16: '1st phase - special contingent (Madeira Island)',
    17: '2nd phase - general contingent',
    18: '3rd phase - general contingent',
    26: 'Ordinance No. 533-A/99, item b2) (Different Plan)',
    27: 'Ordinance No. 533-A/99, item b3 (Other Institution)',
    39: 'Over 23 years old',
    42: 'Transfer',
    43: 'Change of course',
    44: 'Technological specialization diploma holders',
    51: 'Change of institution/course',
    53: 'Short cycle diploma holders',
    57: 'Change of institution/course (International)'
}

# Menerapkan mapping ke kolom baru
df['Application mode'] = data['Application mode'].map(app_mode_map)

# Cek apakah ada yang tidak ter-mapping (NaN)
print(df['Application mode'].value_counts())

Application mode
1st phase - general contingent                         1708
2nd phase - general contingent                          872
Over 23 years old                                       785
Change of course                                        312
Technological specialization diploma holders            213
Holders of other higher courses                         139
3rd phase - general contingent                          124
Transfer                                                 77
Change of institution/course                             59
1st phase - special contingent (Madeira Island)          38
Short cycle diploma holders                              35
International student (bachelor)                         30
1st phase - special contingent (Azores Island)           16
Ordinance No. 854-B/99                                   10
Ordinance No. 612/93                                      3
Change of institution/course (International)              1
Ordinance No. 533-A/99, item b2) (Different Plan)         1
Ordinance No. 533-A/99, item b3 (Other Institution)       1
Name: count, dtype: int64

In [63]:
course_mapping = {
    33: 'Biofuel Production Technologies',
    171: 'Animation and Multimedia Design',
    8014: 'Social Service (evening attendance)',
    9003: 'Agronomy',
    9070: 'Communication Design',
    9085: 'Veterinary Nursing',
    9119: 'Informatics Engineering',
    9130: 'Equinculture',
    9147: 'Management',
    9238: 'Social Service',
    9254: 'Tourism',
    9500: 'Nursing',
    9556: 'Oral Hygiene',
    9670: 'Advertising and Marketing Management',
    9773: 'Journalism and Communication',
    9853: 'Basic Education',
    9991: 'Management (evening attendance)'
}

# Membuat kolom baru agar data angka asli tetap aman
df['Course'] = df['Course'].map(course_mapping)

# Cek 5 data teratas
df["Course"].head()

0        Animation and Multimedia Design
1                                Tourism
2                   Communication Design
3           Journalism and Communication
4    Social Service (evening attendance)
Name: Course, dtype: str

In [64]:
prev_qual_mapping = {
    1: 'Secondary education',
    2: "Higher education - bachelor's degree",
    3: 'Higher education - degree',
    4: "Higher education - master's",
    5: 'Higher education - doctorate',
    6: 'Frequency of higher education',
    9: '12th year of schooling - not completed',
    10: '11th year of schooling - not completed',
    12: 'Other - 11th year of schooling',
    14: '10th year of schooling',
    15: '10th year of schooling - not completed',
    19: 'Basic education 3rd cycle (9th/10th/11th year) or equiv.',
    38: 'Basic education 2nd cycle (6th/7th/8th year) or equiv.',
    39: 'Technological specialization course',
    40: 'Higher education - degree (1st cycle)',
    42: 'Professional higher technical course',
    43: 'Higher education - master (2nd cycle)'
}

df['Previous qualification'] = df['Previous qualification'].map(prev_qual_mapping)

In [65]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,2nd phase - general contingent,5,Animation and Multimedia Design,1,Secondary education,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,International student (bachelor),1,Tourism,1,Secondary education,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1st phase - general contingent,5,Communication Design,1,Secondary education,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,2nd phase - general contingent,2,Journalism and Communication,1,Secondary education,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,Over 23 years old,1,Social Service (evening attendance),0,Secondary education,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [66]:
nacionality_mapping = {
    1: 'Portuguese',
    2: 'German',
    6: 'Spanish',
    11: 'Italian',
    13: 'Dutch',
    14: 'English',
    17: 'Lithuanian',
    21: 'Angolan',
    22: 'Cape Verdean',
    24: 'Guinean',
    25: 'Mozambican',
    26: 'Santomean',
    32: 'Turkish',
    41: 'Brazilian',
    62: 'Romanian',
    100: 'Moldova (Republic of)',
    101: 'Mexican',
    103: 'Ukrainian',
    105: 'Russian',
    108: 'Cuban',
    109: 'Colombian'
}

# Membuat kolom teks untuk EDA
df['Nacionality'] = df['Nacionality'].map(nacionality_mapping)

# Cek distribusi 5 negara terbanyak
df['Nacionality'].tail(5)

4419      Portuguese
4420         Russian
4421      Portuguese
4422      Portuguese
4423    Cape Verdean
Name: Nacionality, dtype: str

In [67]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,2nd phase - general contingent,5,Animation and Multimedia Design,1,Secondary education,122.0,Portuguese,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,International student (bachelor),1,Tourism,1,Secondary education,160.0,Portuguese,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1st phase - general contingent,5,Communication Design,1,Secondary education,122.0,Portuguese,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,2nd phase - general contingent,2,Journalism and Communication,1,Secondary education,122.0,Portuguese,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,Over 23 years old,1,Social Service (evening attendance),0,Secondary education,100.0,Portuguese,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [68]:
mother_qual_mapping = {
    1: 'Secondary Education - 12th Year',
    2: "Higher Education - Bachelor's Degree",
    3: 'Higher Education - Degree',
    4: "Higher Education - Master's",
    5: 'Higher Education - Doctorate',
    6: 'Frequency of Higher Education',
    9: '12th Year - Not Completed',
    10: '11th Year - Not Completed',
    11: '7th Year (Old)',
    12: 'Other - 11th Year',
    14: '10th Year',
    18: 'General commerce course',
    19: 'Basic Education 3rd Cycle (9th-11th Year)',
    22: 'Technical-professional course',
    26: '7th year of schooling',
    27: '2nd cycle of general high school',
    29: '9th Year - Not Completed',
    30: '8th year of schooling',
    34: 'Unknown',
    35: "Can't read or write",
    36: 'Can read without 4th year',
    37: 'Basic education 1st cycle (4th-5th year)',
    38: 'Basic Education 2nd Cycle (6th-8th Year)',
    39: 'Technological specialization course',
    40: 'Higher education - degree (1st cycle)',
    41: 'Specialized higher studies course',
    42: 'Professional higher technical course',
    43: 'Higher Education - Master (2nd cycle)',
    44: 'Higher Education - Doctorate (3rd cycle)'
}

df["Mother's qualification"] = df["Mother's qualification"].map(mother_qual_mapping)

In [69]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,2nd phase - general contingent,5,Animation and Multimedia Design,1,Secondary education,122.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,International student (bachelor),1,Tourism,1,Secondary education,160.0,Portuguese,Secondary Education - 12th Year,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1st phase - general contingent,5,Communication Design,1,Secondary education,122.0,Portuguese,Basic education 1st cycle (4th-5th year),37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,2nd phase - general contingent,2,Journalism and Communication,1,Secondary education,122.0,Portuguese,Basic Education 2nd Cycle (6th-8th Year),37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,Over 23 years old,1,Social Service (evening attendance),0,Secondary education,100.0,Portuguese,Basic education 1st cycle (4th-5th year),38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [70]:
father_qual_mapping = {
    1: 'Secondary Education - 12th Year',
    2: "Higher Education - Bachelor's Degree",
    3: 'Higher Education - Degree',
    4: "Higher Education - Master's",
    5: 'Higher Education - Doctorate',
    6: 'Frequency of Higher Education',
    9: '12th Year - Not Completed',
    10: '11th Year - Not Completed',
    11: '7th Year (Old)',
    12: 'Other - 11th Year',
    13: '2nd year complementary high school',
    14: '10th Year',
    18: 'General commerce course',
    19: 'Basic Education 3rd Cycle (9th-11th Year)',
    20: 'Complementary High School Course',
    22: 'Technical-professional course',
    25: 'Complementary High School - not concluded',
    26: '7th year of schooling',
    27: '2nd cycle of general high school',
    29: '9th Year - Not Completed',
    30: '8th year of schooling',
    31: 'General Course of Admin and Commerce',
    33: 'Supplementary Accounting and Admin',
    34: 'Unknown',
    35: "Can't read or write",
    36: 'Can read without 4th year',
    37: 'Basic education 1st cycle (4th-5th year)',
    38: 'Basic Education 2nd Cycle (6th-8th Year)',
    39: 'Technological specialization course',
    40: 'Higher education - degree (1st cycle)',
    41: 'Specialized higher studies course',
    42: 'Professional higher technical course',
    43: 'Higher Education - Master (2nd cycle)',
    44: 'Higher Education - Doctorate (3rd cycle)'
}

df["Father's qualification"] = df["Father's qualification"].map(father_qual_mapping)

In [71]:
mother_occ_mapping = {
    0: 'Student',
    1: 'Legislative/Executive Directors/Managers',
    2: 'Specialists in Intellectual/Scientific Activities',
    3: 'Intermediate Level Technicians/Professions',
    4: 'Administrative staff',
    5: 'Personal Services/Security/Sellers',
    6: 'Skilled Agricultural/Fisheries/Forestry Workers',
    7: 'Skilled Industry/Construction/Craftsmen',
    8: 'Installation/Machine Operators/Assembly Workers',
    9: 'Unskilled Workers',
    10: 'Armed Forces Professions',
    90: 'Other Situation',
    99: '(blank)',
    122: 'Health professionals',
    123: 'Teachers',
    125: 'ICT Specialists',
    131: 'Intermediate Science/Engineering Technicians',
    132: 'Intermediate Health Technicians',
    134: 'Intermediate Legal/Social/Sports/Cultural Technicians',
    141: 'Office workers/Secretaries/Data Operators',
    143: 'Data/Accounting/Financial/Registry Operators',
    144: 'Other administrative support staff',
    151: 'Personal service workers',
    152: 'Sellers',
    153: 'Personal care workers',
    171: 'Skilled construction workers',
    173: 'Skilled Printing/Precision/Jewelry/Artisans',
    175: 'Food/Wood/Clothing/Crafts Industry Workers',
    191: 'Cleaning workers',
    192: 'Unskilled Agricultural/Fisheries/Forestry Workers',
    193: 'Unskilled Extractive/Construction/Manufacturing Workers',
    194: 'Meal preparation assistants'
}

# Langsung timpa kolom asli di df
df["Mother's occupation"] = df["Mother's occupation"].map(mother_occ_mapping)

# Cek hasil mapping
print(df["Mother's occupation"].value_counts().head(20))

Mother's occupation
Unskilled Workers                                        1577
Administrative staff                                      817
Personal Services/Security/Sellers                        530
Intermediate Level Technicians/Professions                351
Specialists in Intellectual/Scientific Activities         318
Skilled Industry/Construction/Craftsmen                   272
Student                                                   144
Legislative/Executive Directors/Managers                  102
Skilled Agricultural/Fisheries/Forestry Workers            91
Other Situation                                            70
Installation/Machine Operators/Assembly Workers            36
Cleaning workers                                           26
(blank)                                                    17
Meal preparation assistants                                11
Office workers/Secretaries/Data Operators                   8
Teachers                                                    7
Other administrative support staff                          6
Food/Wood/Clothing/Crafts Industry Workers                  5
Unskilled Agricultural/Fisheries/Forestry Workers           5
Intermediate Legal/Social/Sports/Cultural Technicians       4
Name: count, dtype: int64

In [72]:
father_occ_mapping = {
    0: 'Student',
    1: 'Legislative/Executive Directors/Managers',
    2: 'Specialists in Intellectual/Scientific Activities',
    3: 'Intermediate Level Technicians/Professions',
    4: 'Administrative staff',
    5: 'Personal Services/Security/Sellers',
    6: 'Skilled Agricultural/Fisheries/Forestry Workers',
    7: 'Skilled Industry/Construction/Craftsmen',
    8: 'Installation/Machine Operators/Assembly Workers',
    9: 'Unskilled Workers',
    10: 'Armed Forces Professions',
    90: 'Other Situation',
    99: '(blank)',
    101: 'Armed Forces Officers',
    102: 'Armed Forces Sergeants',
    103: 'Other Armed Forces personnel',
    112: 'Directors of administrative/commercial services',
    114: 'Hotel/catering/trade services directors',
    121: 'Specialists in physical sciences/engineering',
    122: 'Health professionals',
    123: 'Teachers',
    124: 'Specialists in finance/admin/relations',
    131: 'Intermediate Science/Engineering Technicians',
    132: 'Intermediate Health Technicians',
    134: 'Intermediate Legal/Social/Sports/Cultural Technicians',
    135: 'ICT Technicians',
    141: 'Office workers/Secretaries/Data Operators',
    143: 'Data/Accounting/Financial Operators',
    144: 'Other administrative support staff',
    151: 'Personal service workers',
    152: 'Sellers',
    153: 'Personal care workers',
    154: 'Protection/Security services personnel',
    161: 'Market-oriented farmers/skilled agri workers',
    163: 'Subsistence farmers/fishers/gatherers',
    171: 'Skilled construction workers',
    172: 'Skilled metallurgy/metalworking workers',
    174: 'Skilled electricity/electronics workers',
    175: 'Food/Wood/Clothing/Crafts Industry Workers',
    181: 'Fixed plant/machine operators',
    182: 'Assembly workers',
    183: 'Vehicle drivers/mobile equipment operators',
    192: 'Unskilled Agri/Fisheries/Forestry Workers',
    193: 'Unskilled Extractive/Construction/Transport Workers',
    194: 'Meal preparation assistants',
    195: 'Street vendors/service providers'
}

# Langsung timpa kolom asli di df
df["Father's occupation"] = df["Father's occupation"].map(father_occ_mapping)

# Cek 5 data teratas untuk memastikan sudah berubah
print(df["Father's occupation"].head())

0                             Unskilled Workers
1    Intermediate Level Technicians/Professions
2                             Unskilled Workers
3    Intermediate Level Technicians/Professions
4                             Unskilled Workers
Name: Father's occupation, dtype: str

In [73]:
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,2nd phase - general contingent,5,Animation and Multimedia Design,1,Secondary education,122.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),Other - 11th Year,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,International student (bachelor),1,Tourism,1,Secondary education,160.0,Portuguese,Secondary Education - 12th Year,Higher Education - Degree,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1st phase - general contingent,5,Communication Design,1,Secondary education,122.0,Portuguese,Basic education 1st cycle (4th-5th year),Basic education 1st cycle (4th-5th year),...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,2nd phase - general contingent,2,Journalism and Communication,1,Secondary education,122.0,Portuguese,Basic Education 2nd Cycle (6th-8th Year),Basic education 1st cycle (4th-5th year),...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,Over 23 years old,1,Social Service (evening attendance),0,Secondary education,100.0,Portuguese,Basic education 1st cycle (4th-5th year),Basic Education 2nd Cycle (6th-8th Year),...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,2nd phase - general contingent,5,Animation and Multimedia Design,1,Secondary education,122.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),Other - 11th Year,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,International student (bachelor),1,Tourism,1,Secondary education,160.0,Portuguese,Secondary Education - 12th Year,Higher Education - Degree,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1st phase - general contingent,5,Communication Design,1,Secondary education,122.0,Portuguese,Basic education 1st cycle (4th-5th year),Basic education 1st cycle (4th-5th year),...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,2nd phase - general contingent,2,Journalism and Communication,1,Secondary education,122.0,Portuguese,Basic Education 2nd Cycle (6th-8th Year),Basic education 1st cycle (4th-5th year),...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,Over 23 years old,1,Social Service (evening attendance),0,Secondary education,100.0,Portuguese,Basic education 1st cycle (4th-5th year),Basic Education 2nd Cycle (6th-8th Year),...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate
5,2,Over 23 years old,1,Management (evening attendance),0,Basic education 3rd cycle (9th/10th/11th year)...,133.1,Portuguese,Basic education 1st cycle (4th-5th year),Basic education 1st cycle (4th-5th year),...,0,5,17,5,11.500000,5,16.2,0.3,-0.92,Graduate
6,1,1st phase - general contingent,1,Nursing,1,Secondary education,142.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),Basic Education 2nd Cycle (6th-8th Year),...,0,8,8,8,14.345000,0,15.5,2.8,-4.06,Graduate
7,1,3rd phase - general contingent,4,Tourism,1,Secondary education,119.0,Portuguese,Basic education 1st cycle (4th-5th year),Basic education 1st cycle (4th-5th year),...,0,5,5,0,0.000000,0,15.5,2.8,-4.06,Dropout
8,1,1st phase - general contingent,3,Social Service,1,Secondary education,137.0,Romanian,Secondary Education - 12th Year,Secondary Education - 12th Year,...,0,6,7,6,14.142857,0,16.2,0.3,-0.92,Graduate
9,1,1st phase - general contingent,1,Social Service,1,Secondary education,138.0,Portuguese,Secondary Education - 12th Year,Basic Education 3rd Cycle (9th-11th Year),...,0,6,14,2,13.500000,0,8.9,1.4,3.51,Dropout
10,1,1st phase - general contingent,1,Advertising and Marketing Management,1,Secondary education,139.0,Portuguese,Basic Education 2nd Cycle (6th-8th Year),Basic Education 3rd Cycle (9th-11th Year),...,0,6,7,5,14.200000,0,13.9,-0.3,0.79,Graduate
11,1,1st phase - general contingent,1,Nursing,1,Secondary education,136.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),Basic Education 2nd Cycle (6th-8th Year),...,0,8,8,7,13.214286,0,12.7,3.7,-1.70,Graduate
12,1,1st phase - general contingent,2,Basic Education,1,Secondary education,133.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),Basic education 1st cycle (4th-5th year),...,0,6,0,0,0.000000,0,12.7,3.7,-1.70,Dropout
13,1,Short cycle diploma holders,1,Tourism,1,Professional higher technical course,110.0,Portuguese,Secondary Education - 12th Year,Secondary Education - 12th Year,...,0,6,8,5,11.000000,0,8.9,1.4,3.51,Graduate
14,1,1st phase - general contingent,1,Veterinary Nursing,1,Secondary education,149.0,Portuguese,Basic Education 2nd Cycle (6th-8th Year),Basic education 1st cycle (4th-5th year),...,0,5,5,5,12.000000,0,10.8,1.4,1.74,Graduate
15,1,1st phase - general contingent,1,Journalism and Communication,1,Secondary education,127.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),Basic education 1st cycle (4th-5th year),...,0,6,7,0,0.000000,0,15.5,2.8,-4.06,Dropout
16,1,3rd phase - general contingent,1,Social Service,1,Secondary education,137.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),Basic Education 2nd Cycle (6th-8th Year),...,0,6,14,2,11.000000,0,10.8,1.4,1.74,Enrolled
17,1,2nd phase - general contingent,2,Nursing,1,Secondary education,135.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),Secondary Education - 12th Year,...,0,8,8,8,14.545000,0,15.5,2.8,-4.06,Graduate
18,1,1st phase - general contingent,1,Equinculture,1,Secondary education,137.0,Portuguese,Higher Education - Degree,Basic Education 3rd Cycle (9th-11th Year),...,0,5,8,4,12.250000,2,10.8,1.4,1.74,Graduate
19,1,1st phase - general contingent,1,Basic Education,1,Secondary education,140.0,Portuguese,Basic Education 3rd Cycle (9th-11th Year),Basic Education 3rd Cycle (9th-11th Year),...,0,7,8,6,13.500000,0,16.2,0.3,-0.92,Enrolled